POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
  "nombres": "prueba",
  "email":"admin@mail.com",
  "password":"admin12345"

}

### Login
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "email":"admin@mail.com",
  "password":"admin12345"
}

### Usuarios
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwiaWQiOjEsImlhdCI6MTcwOTMwNjk1MiwiZXhwIjoxNzA5MzA3MDEyfQ.rypDMTpZkfOGTCjsxq0LmtUbB8gyHqacEtiozRl8-zA